name: CI Build

    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - main

    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - name: Install dependencies
            run: npm install
          - name: Run build
            run: npm run build
          - name: Run tests
            run: npm run test
